### ISSUE TITLE
no template "grafana.fullname" associated with template "gotpl"

### ISSUE THREAD

**Issue by jouve** [rancher/charts#1205]
upgrade to monitoring chart version 14.5.100 fails with this error :
```
---------------------------------------------------------------------
--
SUCCESS:  helm upgrade --history-max=5 --install=true  --namespace=cattle-monitoring-system --timeout=10m0s  --values=/home/shell/helm/values-rancher-monitoring-crd-14.5.100.yaml  --version=14.5.100 --wait=true rancher-monitoring-crd  /home/shell/helm/rancher-monitoring-crd-14.5.100.tgz
---------------------------------------------------------------------
helm  upgrade --history-max=5 --install=true  --namespace=cattle-monitoring-system --timeout=10m0s  --values=/home/shell/helm/values-rancher-monitoring-14.5.100.yaml  --version=14.5.100 --wait=true rancher-monitoring  /home/shell/helm/rancher-monitoring-14.5.100.tgz
Error:  UPGRADE FAILED: template:  rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml:117:13:  executing  "rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml" at  &lt;include "call-nested" (list . "grafana" "grafana.fullname")&gt;:  error calling include: template:  rancher-monitoring/templates/_helpers.tpl:21:4: executing "call-nested"  at &lt;include $template (dict "Chart" (dict "Name" (last $subchart))  "Values" $values "Release" $dot.Release "Capabilities"  $dot.Capabilities)&gt;: error calling include: template: no template  "grafana.fullname" associated with template "gotpl"
--
```

**Comment by devops-leni** [comment]
Hello,

I have the same issue with the chart version 14.5.100 but only when I want to disable the Grafana !

My values file : 
```
grafana:
  enable: false

prometheus:
  prometheusSpec:
    evaluationInterval: 1m
    retentionSize: ${prometheus_retention_size}GiB
    scrapeInterval: 1m
    replicas: ${prometheus_replicas}
    resources:
     ...

rkeControllerManager:
  enabled: true

rkeEtcd:
  enabled: true

rkeProxy:
  enabled: true

rkeScheduler:
  enabled: true
```

The error after the helm upgrade log : 
```
Error: template: rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml:117:13: 
executing "rancher-monitoring/templates/rancher-monitoring/clusterrole.yaml" 
at <include "call-nested" (list . "grafana" "grafana.fullname")>: 
error calling include: template: rancher-monitoring/templates/_helpers.tpl:21:4: 
executing "call-nested" at <include $template (dict "Chart" (dict "Name" (last $subchart)) 
"Values" $values "Release" $dot.Release "Capabilities" $dot.Capabilities)>: 
error calling include: template: no template "grafana.fullname" associated with template "gotpl"
```
