### ISSUE TITLE
fix CI if a helm chart contains a sub charts and it is not packaged as .tgz file

### ISSUE THREAD

**Issue by guangbochen** [rancher/charts#122]
**Problem:**
rancher/chart CI will fail if the helm chart contains a sub-charts and it is not packaged as .tgz file, e.g.
```
Error: directory proposed/istio/charts/sidecarInjectorWebhook not found
Error linting charts
```

```
dependencies:
  - name: sidecarInjectorWebhook
    version: 1.0.5
    condition: sidecarInjectorWebhook.enabled
    repository: "file://../charts/sidecarInjectorWebhook"
  - name: security
    version: 1.0.5
    condition: security.enabled
    repository: "file://../charts/security"
```

**Solution:**
add `helm packages` in the CI validation and auto generates .tgz files for those local charts which uses directory structure.

**Related PRs:**

https://drone8.rancher.io/rancher/charts/223/3
