### ISSUE TITLE
Cannot use affinity in mongodb-replicaset

### ISSUE THREAD

**Issue by marufbd** [rancher/charts#124]
I am using in rancher 2.1.6 for Digital Ocean managed kubernetes 

From catalog apps launching this chart works with default options.

As i want the replicas to be not scheduled to same nodes, when i edit the yaml to add affinity option like this:

```
defaultImage: true
installImage.repository: k8s.gcr.io/mongodb-install
installImage.tag: '0.6'
image.repository: mongo
image.tag: '3.6'
replicas: '3'
port: '27017'
replicaSetName: rs0
auth.enabled: true
auth.key: mongorsauthkey
auth.adminUser: root
auth.adminPassword: secret
persistentVolume.enabled: true
persistentVolume.size: 2Gi
persistentVolume.storageClass: do-block-storage
affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mongodb-replicaset
```

It gets stuck showing installing with following error in ui:

```Failed to install app mongodb-replicaset. Error: release mongodb-replicaset failed: StatefulSet in version "v1beta1" cannot be handled as a StatefulSet: v1beta1.StatefulSet.Spec: v1beta1.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Affinity: readObjectStart: expect { or n, but found ", error found in #10 byte of ...|ffinity":"[object Ob|..., bigger context ...|lease":"mongodb-replicaset"}},"spec":{"affinity":"[object Object]","containers":[{"args":["--config=|...```

The yaml looks valid, not sure if that's a syntax problem. Could not find an example anywhere of any of the option values whose default value is {}, i.e. `nodeSleector`

Tried using affinity as:
```
affinity: {"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["mongodb-replicaset"]}]}}]}}
```

which gives same error.

Changed it like:
```
affinity: '{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["mongodb-replicaset"]}]}}]}}'
```

Now getting error:
`Helm template failed. Error: failed parsing --set data: key "]}}]}}" has no value (cannot end with ,) : exit status 1`
