### ISSUE TITLE
[efk:elasticserch]elasticserch xpack security cannot be enabled

### ISSUE THREAD

**Issue by matsutake78** [rancher/charts#1465]
Chart version： 7.3.0
Kubernetes version： v1.20.8
Helm version： v3.3.3-rancher3

The elastic serch xpack security cannot be enabled. Since editing of elasticserch.yaml is prohibited, I added "xpack.security.enabled: true" in helm as follows, but no error occurs. There is no change in vales.yaml. I tried various methods of addition. Please let me know if you have any advice.

  ```
defaultImage: true
  elasticsearch: 
    image: "ranchercharts/elasticsearch-elasticsearch"
    imageTag: "7.3.0"
    replicas: "3"
    antiAffinity: "hard"
    persistence: 
      enabled: true
      storageClass: "test-sc"
      size: "10Gi"
    xpack.security.enabled: true
```

```
GET _xpack?categories=features&pretty

{
  "features" : {
    "ccr" : {
      "available" : false,
      "enabled" : true
    },
    "data_frame" : {
      "available" : true,
      "enabled" : true
    },
    "flattened" : {
      "available" : true,
      "enabled" : true
    },
    "graph" : {
      "available" : false,
      "enabled" : true
    },
    "ilm" : {
      "available" : true,
      "enabled" : true
    },
    "logstash" : {
      "available" : false,
      "enabled" : true
    },
    "ml" : {
      "available" : false,
      "enabled" : true,
      "native_code_info" : {
        "version" : "7.3.0",
        "build_hash" : "ff2f774f78ce63"
      }
    },
    "monitoring" : {
      "available" : true,
      "enabled" : true
    },
    "rollup" : {
      "available" : true,
      "enabled" : true
    },
    "security" : {
      "available" : true,
      "enabled" : false
    },
    "sql" : {
      "available" : true,
      "enabled" : true
    },
    "vectors" : {
      "available" : true,
      "enabled" : true
    },
    "voting_only" : {
      "available" : true,
      "enabled" : true
    },
    "watcher" : {
      "available" : false,
      "enabled" : true
    }
  },
  "tagline" : "You know, for X"
}
```
