### ISSUE TITLE
[rancher-istio] istio-install-psp not allowing releaseMirror functionality 

### ISSUE THREAD

**Issue by tbrasser** [rancher/charts#1862]
The bundled nginx fails to start because effective uid is not 0 on RKE2 with config:

```yaml
profile: cis-1.6
selinux: true
```

and values:

```yaml
config:
  forceInstall: false
  global:
    rbac:
      pspEnabled: true
  installer:
    releaseMirror:
      enabled: true
```

## Expected behavior

psp allowing privilege escalation so the releaseMirror works as intended.

## Current behavior

`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`
