### ISSUE TITLE
[rancher-monitoring] kube-state-metrics:2.2.0 missing persistentvolumeclaim labels

### ISSUE THREAD

**Issue by strowi** [rancher/charts#2175]
Hi,

while reworking our alerting pipeline i noticed missing labels on the above metric.
I configured the metricsLabelsAllowlist:

```yaml
kube-state-metrics:
  metricLabelsAllowlist:
    - pods=[abc/team]
    - daemonsets=[abc/team]
    - deployments=[abc/team]
    - statefulsets=[abc/team]
    - services=[abc/team]
    - ingresses=[abc/team]
    - namespaces=[abc/team]
    - jobs=[abc/team]
    - persistentvolumeclaims=[abc/team]
```

Added a label to the persistentvolumeclaim, pod, etc.. and also configured the ServiceMonitor to keep those labels.
This seems to work for pods,daemonsets,deployments.. except for the persistentvolumeclaims.
A quick test with kube-state-metrics:2.2.1 seems to solve this (found only [this](https://github.com/kubernetes/kube-state-metrics/pull/1587) on the kube-state-metrics repo).

regards,
strowi
