### ISSUE TITLE
🐮 [fleet] Invalid fleet controller logic on command section (101.0.0+up0.5.0)

### ISSUE THREAD

**Issue by elvishsu66** [rancher/charts#2235]
## Description
The fleet chart v101.0.0+up0.5.0 (template/deployment.yaml) has invalid logic to generate the result. This causes an issue for Rancher v2.7.0 not able to upgrade fleet control for all clusters

Source: 
https://github.com/rancher/charts/blob/7d8d6e83b64cc2fcafd1ee8a638bce8827d68228/charts/fleet/101.0.0%2Bup0.5.0/templates/deployment.yaml#L31-L44

https://github.com/rancher/charts/blob/dev-v2.7/charts/fleet/101.0.0%2Bup0.5.0/templates/deployment.yaml

### Should be
```yaml
        command:
          - fleetcontroller
        {{- if .Values.debug }}
          - --debug
          - --debug-level
          - {{ quote .Values.debugLevel }}
        {{- end }}
        {{- if not .Values.gitops.enabled }}
          - --disable-gitops
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
```
