### ISSUE TITLE
[rancher/kafka] External access doesn't work for brokers

### ISSUE THREAD

**Issue by ceyhunn** [rancher/charts#236]
Kafka broker external access doesn't work with following config:
```
defaultImage: true
image: "confluentinc/cp-kafka"
imageTag: "4.0.1-1"
zookeeper: 
  image: 
    repository: "confluentinc/cp-zookeeper"
    tag: "4.1.1"
  nodeSelector:
    kubernetes.io/hostname: kafkavm
  persistence: 
    enabled: true
    size: "6Gi"
    storageClass: "rook-ceph-block"
schema-registry: 
  image: "confluentinc/cp-schema-registry"
  imageTag: "4.0.1"
  nodeSelector:
    kubernetes.io/hostname: kafkavm
kafka-rest: 
  image: 
    repository: "confluentinc/cp-kafka-rest"
    tag: "4.0.0"
  nodeSelector:
    kubernetes.io/hostname: kafkavm
kafka-topics-ui: 
  image: 
    repository: "landoop/kafka-topics-ui"
    tag: "latest"
  enabled: true
  ingress: 
    enabled: false
    hosts: 
      - "xip.io"
  service: 
    type: "NodePort"
    nodePort: "30100"
  nodeSelector:
    kubernetes.io/hostname: kafkavm
replicas: "3"
persistence: 
  enabled: true
  size: "15Gi"
  storageClass: "rook-ceph-block"
nodeSelector:
  kubernetes.io/hostname: kafkavm
external:
  enabled: true
  servicePort: 9092
  firstListenerPort: 30101

```
