### ISSUE TITLE
[BUG] If taints are specified for windows nodes, fluentbit is not scheduled to nodes.

### ISSUE THREAD

**Issue by herrbpl** [rancher/charts#2477]
### Rancher Server Setup
- Rancher version: 2.6.3
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): EKS

### Information about the Cluster
- Kubernetes version: 1.23
- Cluster Type (Local/Downstream): Hosted EKS

### User Information
- What is the role of the user logged in? Admin/Cluster 

### Describe the bug
When windows nodes in cluster have taint specified, Helm chart to provide fluentbit agents for those nodes does not allow to specify tolerations. This results fluentbit agent not to be scheduled on windows nodes, even when global.cattle.windows.enabled=true

### To Reproduce
1. Spin up EKS cluster with Windows self managed nodes that have any kind of taint specified 
2. Add/import cluster to Rancher
3. Deploy rancher logging operator with global.cattle.windows.enabled=true

### Actual Result
Only linux nodes have fluentbit agent installed

### Expected Result
All nodes have fluentbit agent installed

### Additional context
As workaround, adjust kind Logging rancher-logging-root by adding your toleration to nodeAgents section.

## Recommended fix
Add spec override section to 
```yaml
nodeAgents:
  tls:
    enabled: false
  spec:
    template:
      spec:
        tolerations:
        - ...
```
or if too complicated, just option to specify tolerations for windows nodes as well.

**Comment by herrbpl** [comment]
After more poking around, found out that you can override tolerations in loggingOverlay settings:
```yaml
loggingOverlay:
  spec:
    nodeAgents:
      - name: win-agent
        nodeAgentFluentbit:
          daemonSet:
            spec:
              template:
                spec:
                  containers:
                    - image: rancher/fluent-bit:1.8.9
                      name: fluent-bit
                  tolerations:
                    - effect: NoSchedule
                      key: os
                      value: Win1809
          tls:
            enabled: false
        profile: windows
```

Not sure if this is meant to be like that but it seems to work. Documentation on logging for windows nodes is minimal tho. So, at least it should be documented:
```yaml
global:
  cattle:
    windows:
      enabled: true
       
```
to get windows logging agents installed on EKS cluster.
