### ISSUE TITLE
[BUG] NeuVector Helm chart is not deployable if `cve.scanner.enabled` is set to `true`

### ISSUE THREAD

**Issue by pna-nca** [rancher/charts#2604]
### Rancher Server Setup
- Rancher version: 2.7
- Installation option (Docker install/Helm Chart): N/A
- Proxy/Cert Details: N/A

### Information about the Cluster
N/A

### User Information
N/A

### Provider Information
N/A

### Describe the bug
Commit 6dd5ddc2500fcdeac76b82feadbda8b4c927b743 introduced an error to `packages/neuvector/generated-changes/patch/templates/updater-cronjob.yaml.patch` file.

The generated NeuVector Helm chart package contains a broken `updater-cronjob.yaml` template, `charts/neuvector/102.0.1+up2.4.3/templates/updater-cronjob.yaml` (the same is for `102.0.0+up2.4.2`):

```yaml
...
            - name: neuvector-updater-pod
              image: {{ template "system_default_registry" . }}{{ .Values.cve.updater.image.repository }}:{{ .Values.cve.updater.image.tag }}
              imagePullPolicy: Always
              command:
              - /bin/sh
              - -c
              - sleep 30
          {{- if .Values.cve.scanner.enabled }}
              command:
              - /bin/sh
              - -c
...
```

If `.Values.cve.scanner.enabled` is set to `true`, there will be two `command` instructions which causes the following error during deployment:

```
Error while running post render on files: received error yaml: unmarshal errors: line 31: mapping key "command" already defined at line 27 for the following resource: # Source: neuvector/templates/updater-cronjob.yaml apiVersion: batch/v1 kind: CronJob metadata: name: neuvector-updater-pod namespace: cattle-neuvector-system labels: chart: neuvector-102.0.0_up2.4.2 release: neuvector heritage: Helm spec: schedule: "0 0 * * *" jobTemplate: spec: template: metadata: labels: app: neuvector-updater-pod release: neuvector spec: serviceAccountName: neuvector serviceAccount: neuvector containers: - name: neuvector-updater-pod image: rancher/mirrored-neuvector-updater:latest imagePullPolicy: Always command: - /bin/sh - -c - sleep 30 command: - /bin/sh - -c - /usr/bin/curl -kv -X PATCH -H "Authorization:Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -H "Content-Type:application/strategic-merge-patch+json" -d '{"spec":{"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"'`date +%Y-%m-%dT%H:%M:%S%z`'"}}}}}' '[https://kubernetes.default/apis/apps/v1/namespaces/cattle-neuvector-system/deployments/neuvector-scanner-pod'](https://kubernetes.default/apis/apps/v1/namespaces/cattle-neuvector-system/deployments/neuvector-scanner-pod%27) restartPolicy: Never
```

### To Reproduce
Deploy NeuVector Helm chart from Rancher collection with version `102.0.0+up2.4.2` or `102.0.0+up2.4.2` with `cve.scanner.enabled` set to `true`.

### Actual Result
See the error above.

### Expected Result
Successful deployment.

### Screenshots
N/A

### Additional context
N/A
