### ISSUE TITLE
Possible to reference dependencies from other Rancher custom catalogs

### ISSUE THREAD

**Issue by donovanmuller** [rancher/charts#262]
Is it possible to reference another chart present in a Custom Catalog as a dependency in `requirements.yaml` from a chart in the same or a different Custom Catalog?

I.e. I have a `postgresql` chart in a GitHub repo that I use as the `Catalog URL` and add a new Custom Catalog called `catalog-a`. I then create another Custom Catalog (`catalog-b`) which has a chart in it that needs to reference the `postgresql` chart in the other Custom Catalog (`catcalog-a`) as a dependency in `requirements.yaml`. E.g.

```yaml
dependencies:
  - name: postgresql
    version: 1.0.0
    repository: <? what goes here to reference 'postgres' chart from custom catalog 'catalog-a' ?>
```

Additionally, is it possible to reference the `postgres` chart as a dependency in the _same_ custom catalog (`catalog-b`)?
