### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thystips** [rancher/charts#2769]
### Rancher Server Setup
- Rancher version: v2.7.5
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 v1.24.3+rke2r1
- Proxy/Cert Details: LetsEncrypt

### Information about the Cluster
- Kubernetes version: v1.24.3+rke2r1
- Cluster Type (Local/Downstream): local

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? None
- What is the version of Terraform in use? None

### Describe the bug
Unable to fresh install rancher-monitoring version 102.0.1+up40.1.2 from local helm

### To Reproduce
1.Get values from chart
2. Enable :
  - rke2ControllerManager
  - rke2Scheduler
  - rke2Proxy
  - rke2Etcd
  - rke2IngressNginx
3. Deploy with HELM

```yaml
rke2ControllerManager:
  enabled: true
rke2Scheduler:
  enabled: true
rke2Proxy:
  enabled: true
rke2Etcd:
  enabled: true
rke2IngressNginx:
  enabled: true
  component: kube-system
```

### Actual Result
CrashLoopBackOff on Prometheus Pod.

Logs from init-config-reloader :
```
ts=2023-07-10T14:01:34.863Z caller=main.go:454 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: relabel configuration for replace action requires 'target_label' value"
```

I found this when getting helm values :

```yaml
rke2ControllerManager:
  [...]
  serviceMonitor:
    enabled: true
    endpoints:
      - metricRelabelings:
          - {}
          - {}
```

### Expected Result
Working rancher-monitoring install.

### Additional context
- No issue with older version

**Comment by dtrouillet** [comment]
Hi,

we have the same trouble when we want to upgrade from 102.0.0+up40.1.2 to 102.0.1+up40.1.2.
This file seams to be the problem from line 113 to 120 : https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/102.0.1%2Bup40.1.2/charts/rke2Proxy/templates/_helpers.tpl 


Regards

**Comment by dtrouillet** [comment]
@thystips, can you edit the title of this issue to be more specific please?

**Comment by mdekoster** [comment]
Hi,

We have this problem also when updating from 100.2.0+up40.1.2 to 102.0.1+up40.1.2.

**Comment by Aegis8** [comment]
Hello,

I have just experienced the same problem, when updating to 102.0.1+up40.1.2.

`
msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: relabel configuration for replace action requires 'target_label' value"
`

**Comment by john-nunes** [comment]
Can confirm that deleting the values from rancher-monitoring-kube-controller-manager, rancher-monitoring-kube-etcd, and rancher-monitoring-kube-scheduler ServiceMonitor yaml files
``
      - metricRelabelings:
          - {}
          - {}
```
Will allow the configuration to reload.

**Comment by murand78** [comment]
Installing rancher monitoring using RancherUI works fine.
When installing rancher monitoring using ArgoCD I encountered the problem above

I solved setting in helm values both 

```
global:
  cattle: 
    clusterId: c-nxxxx
    clusterName: cxxxxxxx
```

All the rendered service monitors ( eg rancher-monitoring-kube-etcd) contains :

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher-monitoring-kube-etcd
  namespace: cattle-monitoring-system
  labels: 
    app: rancher-monitoring-kube-etcd
    release: rancher-monitoring
    component: "kube-etcd"
    provider: kubernetes
spec:
  endpoints: 
    - metricRelabelings:
      - action: replace
        replacement: cxxxxxxx
        sourceLabels:
        - __address__
        targetLabel: cluster_name
      - action: replace
        replacement: c-nxxxx
        sourceLabels:
        - __address__
        targetLabel: cluster_id

```
Instead of the config tha caused the issue:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher-monitoring-kube-etcd
  namespace: cattle-monitoring-system
  labels: 
    app: rancher-monitoring-kube-etcd
    release: rancher-monitoring
    component: "kube-etcd"
    provider: kubernetes
spec:
  endpoints: 
    - metricRelabelings:
      - {}
      - {}
```
