### ISSUE TITLE
How to play with requirement.yaml

### ISSUE THREAD

**Issue by disaster37** [rancher/charts#69]
Hi, i try to create new app base on this repository.
I have created requirement.yaml on my app to another app that exist on my repository.

requirement.yaml
```yaml
dependencies:
- name: postgresql
  version: 11.1-1
  repository: http://127.0.0.1:8879/charts #run ($ helm serve .) for local http helm server
```

But when I lauch my application from rancher, I get the following error
```
Helm template failed. Error: found in requirements.yaml, but missing in charts/ directory: postgresql : exit status 1
```

In my repository, I have the app Postgres on `charts/postgresql/v11.1-1`.

I found that I haven't charts directory and requirement.lock on my app, maybee it's my mistake. But how i can create that ?
