### ISSUE TITLE
OpenEBS catalog app failed on volume mount

### ISSUE THREAD

**Issue by BalaBalaYi** [rancher/charts#72]
This issue is first found related with 2 openebs issues:
1. https://github.com/openebs/openebs/issues/1688
2. https://github.com/openebs/openebs/issues/2243

For self testing:
Using rancher v2.1.1 deploy openebs(0.6) by catalog app. Creating a pod with pvc failed with:
![image](https://user-images.githubusercontent.com/23303886/49067023-cf623400-f25d-11e8-8e30-e5692cc164b1.png)

I upgraded the cluster with the suggestion according to the above issue:
kubelet:
```
kubelet:
  extra_binds:
    - "/etc/iscsi:/etc/iscsi"
    - "/sbin/iscsiadm:/sbin/iscsiadm"
    - "/lib/modules"
```

And everything goes fine.  

=============================================================
Then found a similar issue in rancher/rancher:
https://github.com/rancher/rancher/issues/14161

So i checked the iscsiadm version both for host and kubelet:
```
root@test:~# docker exec -it kubelet /bin/bash
root@test:/# iscsiadm -V                                                                                                                                                                    
iscsiadm version 2.0-874
root@test:/# 
root@test:/# 
root@test:/# exit
root@test:~# iscsiadm -V
iscsiadm version 2.0-873
```
Indeed, the version is different.

=============================================================
More test is coming:
Accroding to the openebs docs: https://docs.openebs.io/docs/next/prerequisites.html
![image](https://user-images.githubusercontent.com/23303886/49124328-020c3b00-f2f7-11e8-8dc1-5e57cff0ec21.png)

So i tried the following test:
1. Stop host's open-iscsi service. Redeploy k8s cluster + openebs + app(using openebs) - fail;
2. Remove host's open-iscsi service. Redeploy k8s cluster + openebs + app(using openebs) - success;

It is much clearly that this issue is due to the version of open-iscsi.
BTW, longhorn also use open-iscsi and its not involved in this issue.  So if i want to use both longhorn and openebs i need to modify the cluster settings to let kublet using the host open-iscsi service. 

Seems need some compatible effort.

**Comment by nvoskuilen** [comment]
I suspect it has to do with the jiva.replicas which is default set to 3. In this case a cluster must have at least 3 nodes.

My setup is one cluster and one node (1x bare metal machine) 
- Rancher 2.1.5
- Ubuntu 16.04

Here is what I did to make OpenEBS working:

[Cleanup]
- Remove openebs catalog app, and remove openebs from namespaces
- remove the extra_binds from kubelet (if exists)
- remove open-iscsi from host (if installed)

[On hosts]
Add "iscsi_tcp" (without quotes) to /ect/modules so this will be loaded on reboots, then execute the following commands
```
modprobe iscsi_tcp
mkdir /mnt/openebs-gpd
```

It's time to install OpenEBS from catalog library and wait for it to finish installing.

Now create a new StoragePool where we mount  "/mnt/openebs-gpd" and add  a new StorageClass where we set the jiva replicas to 1. Launch kubectl and paste the following:
```
cat <<EOF | kubectl create -f -
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: gpdpool
  type: hostdir
spec:
  path: "/mnt/openebs-gpd"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva-gpd-1repl
  annotations:
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "1" 
      - name: StoragePool
        value: gpdpool
    openebs.io/cas-type: jiva
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
volumeBindingMode: Immediate
EOF
```
From here we can use this new "openebs-jiva-gpd-1repl" class to create pvc's on a single node.


Note to chart maintainers: Consider making "jiva.replicas" and StoragePool mount path adjustable in the catalog configuration options.
