### ISSUE TITLE
Application Artifactory-Ha requires 3 persistent volumes

### ISSUE THREAD

**Issue by luigidifraia** [rancher/charts#75]
Application: Artifactory-Ha
Template Version: 0.7.6
Expose app using Layer 7 Load Balancer: Yes
Hostname: Automatically generate a .xip.io hostname
Enable Persistent Storage for Artifactory: False

Issue: Pod has unbound PersistentVolumeClaims (repeated 3 times)
- The claims are as per below (allegedly each claim is for a 50 GB PV):
artifactory-ha/volume-artifactory-ha-artifactory-ha-member-0
artifactory-ha/volume-artifactory-ha-artifactory-ha-member-1
artifactory-ha/volume-artifactory-ha-artifactory-ha-primary-0

More than an issue per se, this comes across as an inconsistency: If _Enable Persistent Storage for Artifactory_ is set to _False_, would it be reasonable to expect the application not to have PVCs?

**Comment by guangbochen** [comment]
The Artifactory-HA chart seems to have the PVc enabled as required, you can install the `longhorn` or `nfs-provisoner` from the catalog to get a dynamic storage provisioning or using your own storage server.

@jainishshah17 do u guys have plan to add `emptyDir: {}` as a option for non-PVc  user or it is by design to must add PVc.

**Comment by jainishshah17** [comment]
@luigidifraia Can you please create an issue at https://github.com/jfrog/charts.

**Comment by luigidifraia** [comment]
@jainishshah17 I guess it might not be necessary to create an issue after all. According to the snippet of code that uses its value, the variable `artifactory.persistence.enabled` (which is what is set through Rancher UI's question "Enable Persistent Storage for Artifactory") is not related to claims on persistent volumes, but to an initialization step, _remove-lost-found_:

```
    {{- if .Values.artifactory.persistence.enabled }}
      - name: "remove-lost-found"
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: {{ .Values.artifactory.image.pullPolicy }}
        command:
        - 'sh'
        - '-c'
        - 'rm -rfv {{ .Values.artifactory.persistence.mountPath }}/lost+found'
        volumeMounts:
        - mountPath: {{ .Values.artifactory.persistence.mountPath | quote }}
          name: volume
    {{- end }}
```
