### ISSUE TITLE
rancher-monitoring - Alertmanager overwrites dont work

### ISSUE THREAD

**Issue by oed-mertenss** [rancher/charts#829]
Hello,

i have rancher 2.5 and a rke cluster in 1.18.10. I installed rancher-monitoring via the apps ui.
When changing the alertmanager configuration it is not honored.

This is my Yaml configuation
```yaml
...
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    receivers:
      - name: "null"
      - name: 'prometheus-msteams'
        webhook_configs:
          - send_resolved: true
            url: 'http://prometheus-msteams:2000/test'
...
```

In the Alertmanager itself under "status" just the default config is shown and not my edited stuff.

I tested it already with the default yaml (ui -> add rancher-monitoring -> edit as yaml -> add a receiver (and leave the rest of the 1000 lines like they are) -> install)

It would be awesome if you can help me so i can get the monitoring alive again :)
