### ISSUE TITLE
Persisting Grafana fails due to init RunAs problem

### ISSUE THREAD

**Issue by rotemsh15** [rancher/charts#839]
I'm trying to persist Grafana dashboards and have my chart values look like this:

```
grafana:
    ini:
      auth:
        anonymous: {}
  persistence:
    accessModes:
      - ReadWriteOnce
    annotations: {}
    enabled: true
    existingClaim: grafana-volume
    finalizers:
      - kubernetes.io/pvc-protection
    size: 10Gi
    storageClassName: gp2
    subPath: null
    type: pvc
```

I've tried both existing claim and letting the chart values create a new pvc, whilst the grafana deployment accepts the volume bind, the init container is failing with this:
![image](https://user-images.githubusercontent.com/67632866/98564705-5971fe80-22b5-11eb-86ba-635ab81c4462.png)

Since the source deployment yaml is the Grafana chart, I've had difficulties finding what the problem was until I narrowed it down to this part of the init container config:

```
image: rancher/library-busybox:1.31.1
        imagePullPolicy: IfNotPresent
        name: init-chown-data
        resources: {}
        securityContext:
          runAsUser: 0
```

I've tracked it down to this https://github.com/rancher/charts/blob/fd3dbe7d1443bf38bcadead8cdc74059d7c63e34/charts/grafana/v3.8.6/templates/deployment.yaml

The only thing that resolved the issue for me was adding this to the deployment yml

`runAsNonRoot: false
`
So not sure what would be the correct path here, or might I be doing something wrong.
BTW, I've tested and it seems that changing other values in the chart and upgrading doesn't reset the value on the yaml, so it rather seems as an initial persisting issue.
